version: '3.8'

services:
  ciklum-app:
    image: link-converter
    build: ciklum/ciklum
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://trendyol-db:5432/trendyol-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

  database:
    container_name: trendyol-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=iamgroot
      - POSTGRES_USER=root
      - POSTGRES_DB=trendyol-db
    image: postgres:11.3-alpine




